# Generated by Django 3.0.6 on 2020-05-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200505_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
