# Generated by Django 3.0.6 on 2020-05-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200506_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
